package academy.learnprogramming;

public class Main {

    public static void main(String[] args) {

        char myChar = 'D'; // two bytes of memory, or 16 bits. width of 16
        // it uses two bytes to store unicode characters.
        char myUnicodeChar = '\u0044'; // this is unicode D
        System.out.println(myChar);
        System.out.println(myUnicodeChar);

        boolean myTrueValue = true;
        boolean myFalseValue = false;
        boolean isCustomerOverTwentyOne = true;
        
    }
}
