package academy.learnprogramming;

public class Main {

    public static void main(String[] args) {
	// You understand operator fundamentals
        // Modulo %, returns remainder.
        int result = 4;
        result = result % 3;
        System.out.println(result);

        // Abbreviating operators
        // result = result + 1
        result++; //
        System.out.println(result);
        // result = result - 1
        result--;
        System.out.println(result);
        //result = result + 2
        result += 2;
        System.out.println(result);
        // result = result * 10
        result *= 10;
        System.out.println(result);
        //result = result / 3
        result /= 3;
        System.out.println(result);
        //result = result - 2
        result -= 2;
        System.out.println(result);

        //control flow and if-then. Conditional logic.
        
    }
}
