package academy.learnprogramming;

public class Main {

    public static void main(String[] args) {
        // each of these lines is a statement
	    int myVariable = 50;
	    myVariable++;
	    myVariable--;
        System.out.println("This is a test");

        System.out.println("This is" +
                " another" +
                " still more");
        //
        int anotherVariable = 50;myVariable--;System.out.println("Things can be on the same line, probably shouldn't");
    }
}
